### ISSUE TITLE
最新版本运行出错！

### ISSUE THREAD

**Issue by supperyan** [vondear/RxTool#146]
打开直接闪退！
报错信息如下：
07-09 10:43:02.389 25752-25752/com.vondear.rxdemo E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.vondear.rxdemo, PID: 25752
    java.lang.NoClassDefFoundError: android.support.graphics.drawable.ExposedPathParser
        at com.jaredrummler.android.widget.AnimatedSvgView.rebuildGlyphData(AnimatedSvgView.java:267)
        at com.vondear.rxdemo.activity.ActivitySVG.setSvg(ActivitySVG.java:53)
        at com.vondear.rxdemo.activity.ActivitySVG.onCreate(ActivitySVG.java:43)
        at android.app.Activity.performCreate(Activity.java:6301)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1121)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2455)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2562)
        at android.app.ActivityThread.access$900(ActivityThread.java:165)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1400)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:166)
        at android.app.ActivityThread.main(ActivityThread.java:5610)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:732)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:622)

**Comment by zhangqunshan** [comment]
你是谁啊？？？




| |
张群山
邮箱：18814186735@163.com
|

签名由 网易邮箱大师 定制

在2018年07月09日 10:44，燕朝 写道：

打开直接闪退！
报错信息如下：
07-09 10:43:02.389 25752-25752/com.vondear.rxdemo E/AndroidRuntime: FATAL EXCEPTION: main
Process: com.vondear.rxdemo, PID: 25752
java.lang.NoClassDefFoundError: android.support.graphics.drawable.ExposedPathParser
at com.jaredrummler.android.widget.AnimatedSvgView.rebuildGlyphData(AnimatedSvgView.java:267)
at com.vondear.rxdemo.activity.ActivitySVG.setSvg(ActivitySVG.java:53)
at com.vondear.rxdemo.activity.ActivitySVG.onCreate(ActivitySVG.java:43)
at android.app.Activity.performCreate(Activity.java:6301)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1121)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2455)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2562)
at android.app.ActivityThread.access$900(ActivityThread.java:165)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1400)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:166)
at android.app.ActivityThread.main(ActivityThread.java:5610)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:732)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:622)

**Comment by supperyan** [comment]
github上的项目：vondear/RxTool是你写的吗？
我只是提交一下我运行项目的时候遇到的问题，你应该也是该项目的使用者，只要收藏了该github项目，当有提问时会收到邮件。
所以，我是谁跟问题无关，我也没必要告诉你。

**Comment by zhangqunshan** [comment]
不是我写的github 上我都看别人的项目




| |
张群山
邮箱：18814186735@163.com
|

签名由 网易邮箱大师 定制

在2018年07月09日 11:12，燕朝 写道：

github上的项目：vondear/RxTool是你写的吗？
我只是提交一下我运行项目的时候遇到的问题，你应该也是该项目的使用者，只要收藏了该github项目，当有提问时会收到邮件。
所以，我是谁跟问题无关，我也没必要告诉你。

**Comment by zhangqunshan** [comment]
你把github 地址发我下呗？




| |
张群山
邮箱：18814186735@163.com
|

签名由 网易邮箱大师 定制

在2018年07月09日 11:13，zhangqunshan 写道：
不是我写的github 上我都看别人的项目




| |
张群山
邮箱：18814186735@163.com
|

签名由 网易邮箱大师 定制

在2018年07月09日 11:12，燕朝 写道：

github上的项目：vondear/RxTool是你写的吗？
我只是提交一下我运行项目的时候遇到的问题，你应该也是该项目的使用者，只要收藏了该github项目，当有提问时会收到邮件。
所以，我是谁跟问题无关，我也没必要告诉你。

**Comment by supperyan** [comment]
https://github.com/vondear/RxTool

**Comment by bill556** [comment]
更新这个依赖就好    implementation 'com.jaredrummler:animated-svg-view:1.0.5'    是这个模块的build.gradle依赖问题
